services:
  app:
    container_name: utils
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - utilsnet
  dbutils:
    image: mariadb:10.3
    container_name: dbutils
    tmpfs: /var/lib/mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_DATABASE=testing"
      - "MYSQL_USER=testing"
      - "MYSQL_PASSWORD=secret"
    networks:
      - utilsnet
networks:
  utilsnet:
    driver: bridge